export const regions = [
  "California",
  "Salem",
  "Vancouver",
  "Boulder",
  "Massachusetts",
  "Maryland",
  "Los Angeles",
  "Albany/Corvallis",
  "Colorado",
  "Nevada",
  "Boston",
  "Florida",
  "San Francisco",
  "Washington",
  "Denver",
  "Las Vegas",
  "Ayer",
  "Illinois",
  "Oregon",
  "Seattle",
  "Colorado Springs",
  "Reno",
  "Michigan",
  "Chicago",
  "Portland",
  "Spokane",
  "Fort Collins",
  "Henderson",
  "Detroit",
  "Oklahoma",
];
