export const regions = [
  "California",
  "Salem",
  "Vancouver",
  "Boulder",
  "Massachusetts",
  "Maryland",
  "Los Angeles",
  "Albany/Corvallis",
  "Colorado",
  "Nevada",
  "Boston",
  "Florida",
  "San Francisco",
  "Washington",
  "Denver",
  "Las Vegas",
  "Ayer",
  "Illinois",
  "Oregon",
  "Seattle",
  "Colorado Springs",
  "Reno",
  "Michigan",
  "Chicago",
  "Portland",
  "Spokane",
  "Fort Collins",
  "Henderson",
  "Detroit",
  "Oklahoma",
];

export const brandMockData = [
  {
    title: "KUSHAGRAM",
    rate: "4",
    member: "320",
    count: "270",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: false,
    deliveryTime: "60-90min",
    deliveryFee: "",
    concentrateNumber: "123",
    edibleNumber: "323",
    flowerNumber: "212",
    vapeNumber: "115",
    otherNumber: "121",
    imgUrl: "/images/brands/1.png",
  },

  {
    title: "Amuse Canabis Delivery",
    rate: "4.6",
    member: "235",
    count: "250",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: true,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "167",
    edibleNumber: "124",
    flowerNumber: "213",
    vapeNumber: "215",
    otherNumber: "332",
    imgUrl: "/images/brands/2.png",
  },

  {
    title: "PAC LA - Downtown LA",
    rate: "4.7",
    member: "567",
    count: "643",
    usage: "Medical & Recreational",
    price: "$5 fee, $50 minimum",
    availableOrder: true,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "417",
    edibleNumber: "211",
    flowerNumber: "442",
    vapeNumber: "421",
    otherNumber: "321",
    imgUrl: "/images/brands/3.png",
  },

  {
    title: "HERB",
    rate: "4.9",
    member: "640",
    count: "143",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: false,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "147",
    edibleNumber: "226",
    flowerNumber: "534",
    vapeNumber: "11",
    otherNumber: "21",
    imgUrl: "/images/brands/4.png",
  },

  {
    title: "BLAZE",
    rate: "4.6",
    member: "364",
    count: "213",
    usage: "Medical & Recreational",
    price: "",
    availableOrder: false,
    deliveryTime: "20-30min",
    deliveryFee: "",
    concentrateNumber: "237",
    edibleNumber: "111",
    flowerNumber: "42",
    vapeNumber: "155",
    otherNumber: "671",
    imgUrl: "/images/brands/5.png",
  },
];

export const vapeMockData = [
  {
    title: "Pacific mango Sativa Half Gram Cartridge",
    rate: "4.5",
    member: "320",
    count: "270",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: false,
    deliveryTime: "60-90min",
    deliveryFee: "",
    concentrateNumber: "123",
    edibleNumber: "323",
    flowerNumber: "212",
    vapeNumber: "115",
    otherNumber: "121",
    imgUrl: "/images/brands/vape/batteries/1.png",
  },

  {
    title: "Amuse Canabis Delivery",
    rate: "4.6",
    member: "235",
    count: "250",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: true,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "167",
    edibleNumber: "124",
    flowerNumber: "213",
    vapeNumber: "215",
    otherNumber: "332",
    imgUrl: "/images/brands/vape/batteries/2.png",
  },

  {
    title: "PAC LA - Downtown LA",
    rate: "4.7",
    member: "567",
    count: "643",
    usage: "Medical & Recreational",
    price: "$5 fee, $50 minimum",
    availableOrder: true,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "417",
    edibleNumber: "211",
    flowerNumber: "442",
    vapeNumber: "421",
    otherNumber: "321",
    imgUrl: "/images/brands/vape/batteries/3.png",
  },

  {
    title: "HERB",
    rate: "4.9",
    member: "640",
    count: "143",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: false,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "147",
    edibleNumber: "226",
    flowerNumber: "534",
    vapeNumber: "11",
    otherNumber: "21",
    imgUrl: "/images/brands/vape/batteries/4.png",
  },

  {
    title: "BLAZE",
    rate: "4.6",
    member: "364",
    count: "213",
    usage: "Medical & Recreational",
    price: "",
    availableOrder: false,
    deliveryTime: "20-30min",
    deliveryFee: "",
    concentrateNumber: "237",
    edibleNumber: "111",
    flowerNumber: "42",
    vapeNumber: "155",
    otherNumber: "671",
    imgUrl: "/images/brands/vape/batteries/5.png",
  },
];

export const flowerMockData = [
  {
    title: "Caliva | Reef Leaf - Indica",
    rate: "4.9",
    member: "21",
    count: "13",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: false,
    deliveryTime: "60-90min",
    deliveryFee: "",
    concentrateNumber: "123",
    edibleNumber: "323",
    flowerNumber: "212",
    vapeNumber: "115",
    otherNumber: "121",
    imgUrl: "/images/brands/flower/bud/1.png",
  },

  {
    title: "Featured Farms Infused Pre Rolls - Purple Thai",
    rate: "4.3",
    member: "12",
    count: "42",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: true,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "167",
    edibleNumber: "124",
    flowerNumber: "213",
    vapeNumber: "215",
    otherNumber: "332",
    imgUrl: "/images/brands/flower/bud/2.png",
  },

  {
    title: "Mimosa - Flower 3.5g",
    rate: "4.7",
    member: "567",
    count: "643",
    usage: "Medical & Recreational",
    price: "$5 fee, $50 minimum",
    availableOrder: true,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "417",
    edibleNumber: "211",
    flowerNumber: "442",
    vapeNumber: "421",
    otherNumber: "321",
    imgUrl: "/images/brands/flower/bud/3.png",
  },

  {
    title: "Biscotti - Sungrown - Half Oz",
    rate: "3.9",
    member: "12",
    count: "32",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: false,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "147",
    edibleNumber: "226",
    flowerNumber: "534",
    vapeNumber: "11",
    otherNumber: "21",
    imgUrl: "/images/brands/flower/bud/4.png",
  },

  {
    title: "Denver Cookies(28g)",
    rate: "4.6",
    member: "364",
    count: "213",
    usage: "Medical & Recreational",
    price: "",
    availableOrder: false,
    deliveryTime: "20-30min",
    deliveryFee: "",
    concentrateNumber: "237",
    edibleNumber: "111",
    flowerNumber: "42",
    vapeNumber: "155",
    otherNumber: "671",
    imgUrl: "/images/brands/flower/bud/5.png",
  },
];

export const concentrateMockData = [
  {
    title: "Caliva | Reef Leaf - Indica",
    rate: "4.9",
    member: "21",
    count: "13",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: false,
    deliveryTime: "60-90min",
    deliveryFee: "",
    concentrateNumber: "123",
    edibleNumber: "323",
    flowerNumber: "212",
    vapeNumber: "115",
    otherNumber: "121",
    imgUrl: "/images/brands/flower/bud/1.png",
  },

  {
    title: "Featured Farms Infused Pre Rolls - Purple Thai",
    rate: "4.3",
    member: "12",
    count: "42",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: true,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "167",
    edibleNumber: "124",
    flowerNumber: "213",
    vapeNumber: "215",
    otherNumber: "332",
    imgUrl: "/images/brands/flower/bud/2.png",
  },

  {
    title: "Mimosa - Flower 3.5g",
    rate: "4.7",
    member: "567",
    count: "643",
    usage: "Medical & Recreational",
    price: "$5 fee, $50 minimum",
    availableOrder: true,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "417",
    edibleNumber: "211",
    flowerNumber: "442",
    vapeNumber: "421",
    otherNumber: "321",
    imgUrl: "/images/brands/flower/bud/3.png",
  },

  {
    title: "Biscotti - Sungrown - Half Oz",
    rate: "3.9",
    member: "12",
    count: "32",
    usage: "Medical & Recreational",
    price: "$50 minimum",
    availableOrder: false,
    deliveryTime: "20-30min",
    deliveryFee: "5$",
    concentrateNumber: "147",
    edibleNumber: "226",
    flowerNumber: "534",
    vapeNumber: "11",
    otherNumber: "21",
    imgUrl: "/images/brands/flower/bud/4.png",
  },

  {
    title: "Denver Cookies(28g)",
    rate: "4.6",
    member: "364",
    count: "213",
    usage: "Medical & Recreational",
    price: "",
    availableOrder: false,
    deliveryTime: "20-30min",
    deliveryFee: "",
    concentrateNumber: "237",
    edibleNumber: "111",
    flowerNumber: "42",
    vapeNumber: "155",
    otherNumber: "671",
    imgUrl: "/images/brands/flower/bud/5.png",
  },
];
